also check creds on trusted branches

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -69,21 +69,49 @@ jobs:
     executor: ios-executor
     steps:
       - run: echo "Dummy iOS integ tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
 
   integ_test_android_dummy:
     executor: ios-executor
     steps:
       - run: echo "Dummy Android integ tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
 
   e2e_test_ios_dummy:
     executor: ios-executor
     steps:
       - run: echo "Dummy iOS e2e tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
 
   e2e_test_android_dummy:
     executor: ios-executor
     steps:
       - run: echo "Dummy Android e2e tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
 
   integ_test_ios_dummy_ext:
     executor: ios-executor
