use separate jobs for int and ext integ tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,7 +43,7 @@ jobs:
     steps:
       - install_flutter
       - checkout
-      - run: 
+      - run:
           name: Run Flutter Unit Tests
           command: . .circleci/test_all_plugins.sh flutter-test
 
@@ -112,7 +112,55 @@ jobs:
           else
             echo "Credentials are available. Let's fetch the data!"
           fi
-  
+
+  integ_test_ios_dummy_ext:
+    executor: ios-executor
+    steps:
+      - run: echo "Dummy iOS integ tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
+
+  integ_test_android_dummy_ext:
+    executor: ios-executor
+    steps:
+      - run: echo "Dummy Android integ tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
+
+  e2e_test_ios_dummy_ext:
+    executor: ios-executor
+    steps:
+      - run: echo "Dummy iOS e2e tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
+
+  e2e_test_android_dummy_ext:
+    executor: ios-executor
+    steps:
+      - run: echo "Dummy Android e2e tests"
+      - run: |
+          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+            echo "No AWS_ACCESS_KEY_ID is set! Failing..."
+            exit 1;
+          else
+            echo "Credentials are available. Let's fetch the data!"
+          fi
+
   deploy_dummy:
     executor: build-executor
     steps:
@@ -139,18 +187,42 @@ workflows:
           filters:
             branches:
               only: /pull\/[0-9]+/
+      - integ_test_android_dummy_ext:
+          requires:
+            - request_testing
+      - integ_test_ios_dummy_ext:
+          requires:
+            - request_testing
+      - e2e_test_android_dummy_ext:
+          requires:
+            - request_testing
+      - e2e_test_ios_dummy_ext:
+          requires:
+            - request_testing
       - integ_test_android_dummy:
           requires:
             - request_testing
+          filters:
+            branches:
+              ignore: /pull\/[0-9]+/
       - integ_test_ios_dummy:
           requires:
             - request_testing
+          filters:
+            branches:
+              ignore: /pull\/[0-9]+/
       - e2e_test_android_dummy:
           requires:
             - request_testing
+          filters:
+            branches:
+              ignore: /pull\/[0-9]+/
       - e2e_test_ios_dummy:
           requires:
             - request_testing
+          filters:
+            branches:
+              ignore: /pull\/[0-9]+/
       - request_deploy:
           type: approval
           requires:
@@ -166,5 +238,3 @@ workflows:
       - deploy_dummy:
           requires:
             - request_deploy
-          filters:
-            <<: *releasable_branches
